### ISSUE TITLE
mod_neko conf missing ?

### ISSUE THREAD

**Issue by bablukid** [HaxeFoundation/haxe-debian#1]
I'm trying to config a VM on Ubuntu Precise 32

it seem's that the official haxe and neko packages do not create the neko module for apache2
`a2enmod neko`
gives
`ERROR: Module neko does not exist!`

It should create those files in /etc/apache2/mods-available/

```
neko.conf 

<IfModule mod_neko.c>
        AddHandler neko-handler .n
        DirectoryIndex index.n
</IfModule>

neko.load

LoadModule neko_module /usr/lib/neko/mod_neko2.ndll
```

**Comment by andyli** [comment]
So you're using ppa:haxe/releases, right?
You should install the package "libapache2-mod-neko". Once installed, there should be files, "neko.conf" and "neko.load" installed into "/etc/apache2/mods-available".

**Comment by bablukid** [comment]
yes i'm using the new ppa.
If i correctly understand this https://launchpad.net/~haxe/+archive/ubuntu/releases/+packages?field.name_filter=&field.status_filter=published&field.series_filter=precise

it means that libapache2-mod-neko is already included as a subpackage, so I dont understand why it's not been installed.

**Comment by andyli** [comment]
This is the funny relationship between source/bin packages:

The page you mentioned group things by the source packages.
A source package (neko) can build several binary packages(neko, libneko0, libapache2-mod-neko, neko-dev).

When using a apt-get, it will install the binary package of the provided name. It means if you do `apt-get install neko`, it will install the neko binary package together with its dependencies - the neko binary package does not depend on libapache2-mod-neko. That means you have to `apt-get install libapache2-mod-neko` separately.

**Comment by bablukid** [comment]
thanks for your answer.
BTW is there an up to date tutorial on how to install neko with apache / mysql on the latest Ubuntus ?
Each time I have to do it, I spend hours and hours struggling ....

There is a lot of tricks to know : only apache prefork , do not work on apache 2.4 , better to use 2.2 , but how can I install a apache 2.2 on newer distribs which include apache2.4 by default ? ...etc ...etc

It really needs a good level in system administration to escape from all of these issues, that's why it could be very nice to maintain a tutorial about this on haxe.org for newbies like me :)

**Comment by andyli** [comment]
Seriously I have no experience on mod_neko so I can't help. I would also like to read a detailed doc on mod_neko (and mod_tora) such that I can verify and improve the packages... Ping @ncannasse.

**Comment by bablukid** [comment]
Woot ! I succesfully installed mod_neko on a Ubuntu Trusty 64 ( Virtualbox/Vagrant ) with Apache 2.4 in prefork mode (default state after install)

```
sudo add-apt-repository ppa:haxe/releases -y
sudo apt-get update
sudo apt-get install haxe -y
mkdir ~/haxelib && haxelib setup ~/haxelib

apt-get install apache2 mysql-server libapache2-mod-neko

a2enmod rewrite

create a vhost in /etc/apache2/sites-available/mySite  :
<VirtualHost *:80>
  ServerName mySite
  DirectoryIndex index.n
  DocumentRoot /vagrant/mySite/www/
</VirtualHost>

a2ensite mySite

modify apache2.conf for directories outside /var/www

<Directory /vagrant/>
      Options Indexes FollowSymLinks
      AllowOverride All
      Require all granted
</Directory>


```
